# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lt < Formula
  desc "Marine-themed multi-agent workspace manager (Camp Leatherneck — fork of Gas Town)"
  homepage "https://github.com/camp-leatherneck/camp-leatherneck"
  version "0.1.0-pre.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.0-pre.1/camp-leatherneck_0.1.0-pre.1_darwin_amd64.tar.gz"
      sha256 "5b424d878e2f5d4fcc331fc3dccd4b6899b86a9f541151ab0412bad75a64230d"

      define_method(:install) do
        bin.install "lt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.0-pre.1/camp-leatherneck_0.1.0-pre.1_darwin_arm64.tar.gz"
      sha256 "2578f200d7ca7fc78077a218645c3c3de3447615b87d680a7a2db0aa1481e5dd"

      define_method(:install) do
        bin.install "lt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.0-pre.1/camp-leatherneck_0.1.0-pre.1_linux_amd64.tar.gz"
      sha256 "76cea206e2bb1a6268411735cc9aa7663239f729531443ec45246d01530ca32e"
      define_method(:install) do
        bin.install "lt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.0-pre.1/camp-leatherneck_0.1.0-pre.1_linux_arm64.tar.gz"
      sha256 "3c31d54364fb93c7edf91253a54f3f28c07d046013a9e02dcd7f016e471367dd"
      define_method(:install) do
        bin.install "lt"
      end
    end
  end

  test do
    system "#{bin}/lt", "--version"
  end
end
