# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lt < Formula
  desc "Marine-themed multi-agent workspace manager (Camp Leatherneck — fork of Gas Town)"
  homepage "https://github.com/camp-leatherneck/camp-leatherneck"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.1/camp-leatherneck_0.1.1_darwin_amd64.tar.gz"
      sha256 "557d8cd3767b2e9ecf164fd7eabceb750a8374f1795e6687df7c30b4140473e6"

      define_method(:install) do
        bin.install "lt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.1/camp-leatherneck_0.1.1_darwin_arm64.tar.gz"
      sha256 "e384742f5d869d944b36c6f6ede6fb49376b07880100ff419ca3829e9b959c75"

      define_method(:install) do
        bin.install "lt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.1/camp-leatherneck_0.1.1_linux_amd64.tar.gz"
      sha256 "675e5414cbb41c52318e16bdadc97decf89c4c89c809518ae84bd2cc66d8a327"
      define_method(:install) do
        bin.install "lt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/camp-leatherneck/camp-leatherneck/releases/download/v0.1.1/camp-leatherneck_0.1.1_linux_arm64.tar.gz"
      sha256 "57ddf14401da7291c929f772d60aa0d067e147eb8641c67253cd324396258f7a"
      define_method(:install) do
        bin.install "lt"
      end
    end
  end

  test do
    system "#{bin}/lt", "--version"
  end
end
